### ISSUE TITLE
Running RMLio test cases

### ISSUE THREAD

**Issue by pheyvaer** [semantifyit/RocketRML#2]
Hi,

I'm trying to the run the tests, specifically the RMLio test cases. However, the documentation doesn't specify how they should be run. I tried with `npm test`, but I don't think that includes the RMLio ones, or does it? I also executed `node tests/RMLio-testCases/rmlio-tests.js`. This gave me test results, but also some errors. Is this the correct way to run these test cases? And what do the different outputs/errors mean?

Ideally, we would like to add RocketRML to the [RML Implementation Report](http://rml.io/implementation-report/#rml-processor), and for this we need to have the test case results.

**Comment by philipphaeusle** [comment]
Hi,

Yes, node tests/RMLio-testCases/rmlio-tests.js needs to be executed to run the RMLio test cases. First all mappings are executed and also some errors thrown (like in RMLTC0012d-XML the source is looking for persons.json, but there only exists persons.xml), but these errors are correctly thrown.

After all mappings are executed, the generated rdf is compared with the expected output from RMLio.
If it matches, a SUCCESS: RMLTCXXXX line is printed, if there were some differences, the line is where the difference occured is printed twice (first the expected and then the current result).
Please make sure you have https://www.npmjs.com/package/colors installed, so you can also see coloured feedback.
All tests that contain a graphmap are failing because rocketrml does not support graph mappings (not really failing, but the graaph is missing), and also the mappings that contain blanknodes do create a difference because the blanknodes are renamed when the json is converted to n-quads (but this is still correct).

Here you can see an overview of the outcome:
https://docs.google.com/document/d/1Ans3Yzchhvwu9W3s1LQbq4B5IP7Lyy0yJhNgxs8s8vw/edit?usp=sharing

Best, Philipp

**Comment by pheyvaer** [comment]
Ok thanks. I'll see if I can distil all the required information from that. Also, I see from another test case that CSV is supported. So can the RMLio test cases for CSV also be included or is there a reason to leave them out?

**Comment by philipphaeusle** [comment]
It was just a proof of concept, but i now fixed some issues with csv, and added the tests.
